export { default as Extras } from './Extras'
export { default as Footer } from './Footer'
export { default as Navbar } from './Navbar'
export { default as Welcome } from './Welcome'
export { default as Contact } from './Contact'
export { default as PageNotFound } from './PageNotFound'